# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/epu/Documents/SI4/ANCOO/projetRobot

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/epu/Documents/SI4/ANCOO/projetRobot

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/epu/Documents/SI4/ANCOO/projetRobot/CMakeFiles /home/epu/Documents/SI4/ANCOO/projetRobot/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/epu/Documents/SI4/ANCOO/projetRobot/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main.exe

# Build rule for target.
main.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main.exe
.PHONY : main.exe

# fast build rule for target.
main.exe/fast:
	$(MAKE) -f CMakeFiles/main.exe.dir/build.make CMakeFiles/main.exe.dir/build
.PHONY : main.exe/fast

src/EtatRobot.o: src/EtatRobot.cpp.o
.PHONY : src/EtatRobot.o

# target to build an object file
src/EtatRobot.cpp.o:
	$(MAKE) -f CMakeFiles/main.exe.dir/build.make CMakeFiles/main.exe.dir/src/EtatRobot.cpp.o
.PHONY : src/EtatRobot.cpp.o

src/EtatRobot.i: src/EtatRobot.cpp.i
.PHONY : src/EtatRobot.i

# target to preprocess a source file
src/EtatRobot.cpp.i:
	$(MAKE) -f CMakeFiles/main.exe.dir/build.make CMakeFiles/main.exe.dir/src/EtatRobot.cpp.i
.PHONY : src/EtatRobot.cpp.i

src/EtatRobot.s: src/EtatRobot.cpp.s
.PHONY : src/EtatRobot.s

# target to generate assembly for a file
src/EtatRobot.cpp.s:
	$(MAKE) -f CMakeFiles/main.exe.dir/build.make CMakeFiles/main.exe.dir/src/EtatRobot.cpp.s
.PHONY : src/EtatRobot.cpp.s

src/EtatRobotEnChargeFacePlot.o: src/EtatRobotEnChargeFacePlot.cpp.o
.PHONY : src/EtatRobotEnChargeFacePlot.o

# target to build an object file
src/EtatRobotEnChargeFacePlot.cpp.o:
	$(MAKE) -f CMakeFiles/main.exe.dir/build.make CMakeFiles/main.exe.dir/src/EtatRobotEnChargeFacePlot.cpp.o
.PHONY : src/EtatRobotEnChargeFacePlot.cpp.o

src/EtatRobotEnChargeFacePlot.i: src/EtatRobotEnChargeFacePlot.cpp.i
.PHONY : src/EtatRobotEnChargeFacePlot.i

# target to preprocess a source file
src/EtatRobotEnChargeFacePlot.cpp.i:
	$(MAKE) -f CMakeFiles/main.exe.dir/build.make CMakeFiles/main.exe.dir/src/EtatRobotEnChargeFacePlot.cpp.i
.PHONY : src/EtatRobotEnChargeFacePlot.cpp.i

src/EtatRobotEnChargeFacePlot.s: src/EtatRobotEnChargeFacePlot.cpp.s
.PHONY : src/EtatRobotEnChargeFacePlot.s

# target to generate assembly for a file
src/EtatRobotEnChargeFacePlot.cpp.s:
	$(MAKE) -f CMakeFiles/main.exe.dir/build.make CMakeFiles/main.exe.dir/src/EtatRobotEnChargeFacePlot.cpp.s
.PHONY : src/EtatRobotEnChargeFacePlot.cpp.s

src/EtatRobotEnRoute.o: src/EtatRobotEnRoute.cpp.o
.PHONY : src/EtatRobotEnRoute.o

# target to build an object file
src/EtatRobotEnRoute.cpp.o:
	$(MAKE) -f CMakeFiles/main.exe.dir/build.make CMakeFiles/main.exe.dir/src/EtatRobotEnRoute.cpp.o
.PHONY : src/EtatRobotEnRoute.cpp.o

src/EtatRobotEnRoute.i: src/EtatRobotEnRoute.cpp.i
.PHONY : src/EtatRobotEnRoute.i

# target to preprocess a source file
src/EtatRobotEnRoute.cpp.i:
	$(MAKE) -f CMakeFiles/main.exe.dir/build.make CMakeFiles/main.exe.dir/src/EtatRobotEnRoute.cpp.i
.PHONY : src/EtatRobotEnRoute.cpp.i

src/EtatRobotEnRoute.s: src/EtatRobotEnRoute.cpp.s
.PHONY : src/EtatRobotEnRoute.s

# target to generate assembly for a file
src/EtatRobotEnRoute.cpp.s:
	$(MAKE) -f CMakeFiles/main.exe.dir/build.make CMakeFiles/main.exe.dir/src/EtatRobotEnRoute.cpp.s
.PHONY : src/EtatRobotEnRoute.cpp.s

src/EtatRobotFige.o: src/EtatRobotFige.cpp.o
.PHONY : src/EtatRobotFige.o

# target to build an object file
src/EtatRobotFige.cpp.o:
	$(MAKE) -f CMakeFiles/main.exe.dir/build.make CMakeFiles/main.exe.dir/src/EtatRobotFige.cpp.o
.PHONY : src/EtatRobotFige.cpp.o

src/EtatRobotFige.i: src/EtatRobotFige.cpp.i
.PHONY : src/EtatRobotFige.i

# target to preprocess a source file
src/EtatRobotFige.cpp.i:
	$(MAKE) -f CMakeFiles/main.exe.dir/build.make CMakeFiles/main.exe.dir/src/EtatRobotFige.cpp.i
.PHONY : src/EtatRobotFige.cpp.i

src/EtatRobotFige.s: src/EtatRobotFige.cpp.s
.PHONY : src/EtatRobotFige.s

# target to generate assembly for a file
src/EtatRobotFige.cpp.s:
	$(MAKE) -f CMakeFiles/main.exe.dir/build.make CMakeFiles/main.exe.dir/src/EtatRobotFige.cpp.s
.PHONY : src/EtatRobotFige.cpp.s

src/Main.o: src/Main.cpp.o
.PHONY : src/Main.o

# target to build an object file
src/Main.cpp.o:
	$(MAKE) -f CMakeFiles/main.exe.dir/build.make CMakeFiles/main.exe.dir/src/Main.cpp.o
.PHONY : src/Main.cpp.o

src/Main.i: src/Main.cpp.i
.PHONY : src/Main.i

# target to preprocess a source file
src/Main.cpp.i:
	$(MAKE) -f CMakeFiles/main.exe.dir/build.make CMakeFiles/main.exe.dir/src/Main.cpp.i
.PHONY : src/Main.cpp.i

src/Main.s: src/Main.cpp.s
.PHONY : src/Main.s

# target to generate assembly for a file
src/Main.cpp.s:
	$(MAKE) -f CMakeFiles/main.exe.dir/build.make CMakeFiles/main.exe.dir/src/Main.cpp.s
.PHONY : src/Main.cpp.s

src/Objet.o: src/Objet.cpp.o
.PHONY : src/Objet.o

# target to build an object file
src/Objet.cpp.o:
	$(MAKE) -f CMakeFiles/main.exe.dir/build.make CMakeFiles/main.exe.dir/src/Objet.cpp.o
.PHONY : src/Objet.cpp.o

src/Objet.i: src/Objet.cpp.i
.PHONY : src/Objet.i

# target to preprocess a source file
src/Objet.cpp.i:
	$(MAKE) -f CMakeFiles/main.exe.dir/build.make CMakeFiles/main.exe.dir/src/Objet.cpp.i
.PHONY : src/Objet.cpp.i

src/Objet.s: src/Objet.cpp.s
.PHONY : src/Objet.s

# target to generate assembly for a file
src/Objet.cpp.s:
	$(MAKE) -f CMakeFiles/main.exe.dir/build.make CMakeFiles/main.exe.dir/src/Objet.cpp.s
.PHONY : src/Objet.cpp.s

src/Plot.o: src/Plot.cpp.o
.PHONY : src/Plot.o

# target to build an object file
src/Plot.cpp.o:
	$(MAKE) -f CMakeFiles/main.exe.dir/build.make CMakeFiles/main.exe.dir/src/Plot.cpp.o
.PHONY : src/Plot.cpp.o

src/Plot.i: src/Plot.cpp.i
.PHONY : src/Plot.i

# target to preprocess a source file
src/Plot.cpp.i:
	$(MAKE) -f CMakeFiles/main.exe.dir/build.make CMakeFiles/main.exe.dir/src/Plot.cpp.i
.PHONY : src/Plot.cpp.i

src/Plot.s: src/Plot.cpp.s
.PHONY : src/Plot.s

# target to generate assembly for a file
src/Plot.cpp.s:
	$(MAKE) -f CMakeFiles/main.exe.dir/build.make CMakeFiles/main.exe.dir/src/Plot.cpp.s
.PHONY : src/Plot.cpp.s

src/Robot.o: src/Robot.cpp.o
.PHONY : src/Robot.o

# target to build an object file
src/Robot.cpp.o:
	$(MAKE) -f CMakeFiles/main.exe.dir/build.make CMakeFiles/main.exe.dir/src/Robot.cpp.o
.PHONY : src/Robot.cpp.o

src/Robot.i: src/Robot.cpp.i
.PHONY : src/Robot.i

# target to preprocess a source file
src/Robot.cpp.i:
	$(MAKE) -f CMakeFiles/main.exe.dir/build.make CMakeFiles/main.exe.dir/src/Robot.cpp.i
.PHONY : src/Robot.cpp.i

src/Robot.s: src/Robot.cpp.s
.PHONY : src/Robot.s

# target to generate assembly for a file
src/Robot.cpp.s:
	$(MAKE) -f CMakeFiles/main.exe.dir/build.make CMakeFiles/main.exe.dir/src/Robot.cpp.s
.PHONY : src/Robot.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... main.exe"
	@echo "... rebuild_cache"
	@echo "... src/EtatRobot.o"
	@echo "... src/EtatRobot.i"
	@echo "... src/EtatRobot.s"
	@echo "... src/EtatRobotEnChargeFacePlot.o"
	@echo "... src/EtatRobotEnChargeFacePlot.i"
	@echo "... src/EtatRobotEnChargeFacePlot.s"
	@echo "... src/EtatRobotEnRoute.o"
	@echo "... src/EtatRobotEnRoute.i"
	@echo "... src/EtatRobotEnRoute.s"
	@echo "... src/EtatRobotFige.o"
	@echo "... src/EtatRobotFige.i"
	@echo "... src/EtatRobotFige.s"
	@echo "... src/Main.o"
	@echo "... src/Main.i"
	@echo "... src/Main.s"
	@echo "... src/Objet.o"
	@echo "... src/Objet.i"
	@echo "... src/Objet.s"
	@echo "... src/Plot.o"
	@echo "... src/Plot.i"
	@echo "... src/Plot.s"
	@echo "... src/Robot.o"
	@echo "... src/Robot.i"
	@echo "... src/Robot.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

